name: Build-test
on: 
 push:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch 
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          token: ${{ secrets.PAT }}
          repository: pchachicho/helx-ui-action-testing
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'