name: Build-Push-Release-Remote
on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - README.md
      - .old_cicd/*
      # - .github/*
      # - .github/workflows/*
      - LICENSE
      - .gitignore
      - .dockerignore
      - .githooks
    tags-ignore:
      - "v[0-9]+.[0-9]+.*"
jobs:
  build-push-release-remote:
    uses: pchachicho/appstore-action-testing/.github/workflows/test-remote.yml@main
    secrets: inherit
