name: trivy-pr-scan 
on:

  pull_request:
    branches:
      - develop
      - master
      - main 
    types: [ opened, synchronize ]
    paths-ignore:
    - README.md
    # - .old_cicd/*
    # - .github/*
    # - .github/workflows/*
    - LICENSE
    - .gitignore
    - .dockerignore
    - .githooks
 # test trivy later with push instead of pull request
jobs:
    trivy-pr-scan:
        uses: pchachicho/renci-github-actions/.github/workflows/trivy-pr-scan.yml@main
        secrets: inherit
